name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # ВАЖНО

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          ssh monitoring@192.168.100.40 '
            if [ ! -d ~/monitoring ]; then
              git clone https://github.com/USERNAME/REPO.git ~/monitoring
            else
              cd ~/monitoring && git pull
            fi

            cd ~/monitoring/docker
            docker-compose up -d
          '
