name: Deploy Monitoring

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no \
          -J router@192.168.122.66 \
          monitoring@192.168.100.40 \
          'cd monitoring && git pull && docker-compose up -d'
